### ISSUE TITLE
sometimes returns invalid matching

### ISSUE THREAD

**Issue by florian-venn** [dilsonpereira/Minimum-Cost-Perfect-Matching#1]
Sometimes returs invalid matching (compiled with : gcc version 7.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project))

./example.exe -f falsify.txt --minweight
Optimal matching cost: 6
Edges in the matching:
0 1
2 4
4 5

[falsify.txt](https://github.com/dilsonpereira/Minimum-Cost-Perfect-Matching/files/2845728/falsify.txt)

[removed unnecessary edges falsify.txt](https://github.com/dilsonpereira/Minimum-Cost-Perfect-Matching/files/2845900/falsify.txt)

**Comment by dilsonpereira** [comment]
Indeed. It seems to be a bug in the blossom expansion. I think I have a fix for it, I'll add it later today, as soon as I'm sure it won't cause other bugs.

Thank you.

**Comment by dilsonpereira** [comment]
It seems to be fixed now.
