### ISSUE TITLE
Access Violation during Grow()

### ISSUE THREAD

**Issue by florian-venn** [dilsonpereira/Minimum-Cost-Perfect-Matching#2]
Hey thanks for fixing the last issue. I ran into another problem. Sometimes your code crashes for me during Matching::Grow calls.
I attached a small python fuzzer that tries to match random graphs with 50 nodes. After a few seconds it crashes for me. Again compiled with gcc version 7.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project).

[Minimum-Cost-Perfect-Matching.zip](https://github.com/dilsonpereira/Minimum-Cost-Perfect-Matching/files/2852089/Minimum-Cost-Perfect-Matching.zip)

**Comment by dilsonpereira** [comment]
Thank you. I'll look into it.

**Comment by dilsonpereira** [comment]
Fixed. Small bug on the function for augmenting blossoms.
The original code I wrote for my thesis is very reliable, but also ugly. So, before submitting it here I tried reorganizing it. It seems I inserted a few bugs in the process.
Let me know if you have any other issue.
