### ISSUE TITLE
invalid matching

### ISSUE THREAD

**Issue by wang20150419** [dilsonpereira/Minimum-Cost-Perfect-Matching#4]
Sometimes right, sometimes wrong.

The following is example of invalid matching:

 #test file begin
  34
  42
  0  1 10
  1  2 6
  2  3 10
  3  4 6
  4  5 10
  5  6 6
  6  7 10
  8  0 10
  9  8 10
  7 10 10
 11 12 10
 12  9 10
 13 14 6
 14 11 10
 15 16 10
 17 18 10
 18 19 6
 19 13 10
 20 21 6
 21 22 10
 10 23 4
 23 20 10
 22 24 6
 24 15 6
 16 25 4
 25 17 10
  5  0 10
 12 26 10
 26 27 6
 28 29 6
 29 11 10
 28 27 10
 27 23 6
 28 24 4
 30 25 6
  9 31 10
 31 10 6
 32 29 6
 30 13 10
 30 32 10
 33  7 6
 33  8 10
 #test file end

The invalid matching edges:
5  0
10  7
9  8
13  14
14  11
29  11
11  12
29  11
11  14
14  13
27  23
28  24
30  25
Solution cost: 440

How to fix it?

**Comment by dilsonpereira** [comment]
Hi. I ran the code with your input and it gives me the following output, which seems to be correct:
Optimal matching cost: 124
Edges in the matching:
1 2
3 4
5 6
8 0
11 12
13 14
15 16
18 19
20 21
10 23
22 24
25 17
26 27
28 29
9 31
30 32
33 7

**Comment by wang20150419** [comment]
> Hi. I ran the code with your input and it gives me the following output, which seems to be correct:
> Optimal matching cost: 124
> Edges in the matching:
> 1 2
> 3 4
> 5 6
> 8 0
> 11 12
> 13 14
> 15 16
> 18 19
> 20 21
> 10 23
> 22 24
> 25 17
> 26 27
> 28 29
> 9 31
> 30 32
> 33 7

I am sorry that I misled you due to a problem in my presentation. Actually, this is the result of the Chinese Postman Problem.

I used your algorithm to solve the Chinese Postman Problem and found that it was a mistake in the perfect matching algorithm that led to the wrong solution. So I'm posting the problem here.
The  above text is the result of insert print code in line 98 of ChinesePostman.h to display the added edge.

                        while (w != -1)
			{
				A[w].push_back(v);
				A[v].push_back(w);
				printf("\n%d  %d", v, w);  //display added edge, line 98 of ChinesePostman.h
				v = w;
				w = shortestPath[u][v];
			}

See the red line segment in the image. Obviously, three of the new edges( 29->11, 11->14, 14->13 ) are redundant, causing the odd point  to remain an odd point ( point: 29, 11, 13 ),  So the solution fails.

![image](https://user-images.githubusercontent.com/12016822/124787577-25052e00-df7b-11eb-845b-51f65904a7ba.png)


There are some cases where your program works well and gets a very perfect result. Thank you for all your hard work. I am very much looking forward to the fix of this issue. I can provide more error cases if necessary.

**Comment by dilsonpereira** [comment]
Can you please update your copy of the chinese postman code and check if the problem is solved?

**Comment by wang20150419** [comment]
> Can you please update your copy of the chinese postman code and check if the problem is solved?

The bug has been fixed!
Thank you for helping me, I really appreciate it.

**Comment by dilsonpereira** [comment]
Great. I fixed a bug in the matching code a while ago and I thought it would be automatically broadcast to the repos that depended on it. I was wrong and manually updating the chinese postman code with the current matching code seems to have fixed the bug you were experiencing.
