### ISSUE TITLE
Does edge weight data type need to be double?

### ISSUE THREAD

**Issue by karlosss** [dilsonpereira/Minimum-Cost-Perfect-Matching#6]
Hi!
Is there a reason for the data type of edge weight being a double? I found multiple libraries doing that, and I am wondering if for whatever reason that is a must, or a 64bit integers (or even unlimited integers with some bignum arithmetic library) would also do the job.
Great work, by the way!

**Comment by dilsonpereira** [comment]
Hi.
The reason is that double is more general than integer. (I'm not sure I
understand your question correctly)
If you input integers to the algorithm, it's gonna work just fine.
Maybe your question is why doesn't the algorithm use just integer numbers
all around. The reason is that even if the inputs were integers, by the
nature of the primal-dual algorithm, real valued quantities would arise.
You could of course replace the doubles with large enough integers, but
that is not ideal, unless you really have to for some reason.

Regards.
Dilson

**Comment by karlosss** [comment]
Hi Dilson, thank you for quick answer! I would like to use the algorithm you wrote, but my issue is that my edge weights are too large for doubles, therefore I wonder if there would be any way to have the weight data type as a template parameter for example. I did not study the details of the algorithm so I am not really following the issue with the primal-dual algorithm you mention, so I will just trust you there if you say that it has to be doubles no matter what :).
Best,
Karel

**Comment by karlosss** [comment]
Hi Dilson,

by trial and error, I used arbitraty precision floats and the algorithm seems to work fine. If it is easy enough for you to see, could you confirm that it actually does not break the soundness? And would the same be true for unlimited integers?

Best,
Karel

**Comment by dilsonpereira** [comment]
If the floats you're using offer a reasonable amount of decimal places,
then you're likely fine.
As for unlimited integers, if you multiply your input by some large power
of 10 and then truncate them, then it should work (even if the input is
already composed of large numbers, you still have to multiply them by a
large power of 10).
I cannot offer you a guarantee, though.

**Comment by karlosss** [comment]
What should I see behind "reasonable" and "large power of 10"? Is it more that double of the bits would be enough, or rather even more? If, say, my highest edge cost would be 2^90, would it be enough to multiply the inputs by another 2^90 (roughly 10^30), or rather even more? I understand you cannot offer me a guarantee, but your qualified guess is still way better than my qualified guess.

**Comment by dilsonpereira** [comment]
7 or 8 decimal places should be enough. So if you multiply your input by
10**8 you're likely fine (if you can correctly handle these large numbers)

**Comment by karlosss** [comment]
I will try with that, thank you!

**Comment by karlosss** [comment]
Thank you for the support, it actually seems to work stellar! Just if you care what people use your thingy for :) https://github.com/karlosss/swisspair

**Comment by dilsonpereira** [comment]
That's pretty cool. Good job.
